services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports: []
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: []
    environment:
      # Example environment variables, as needed
      - GF_SERVER_ROOT_URL=http://grafana.local
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped


  nginx:
    image: nginx
    ports:
      - "443:443"
    
    depends_on:
      - grafana
      - jenkins

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./passwd/.htpasswd:/etc/nginx/.htpasswd:ro

volumes:
  jenkins_home:
  grafana_storage:
  default.conf:
  certs:
  .htpasswd: